# Generated by Django 6.0.6 on 2026-07-07 09:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="plan_activated_on",
        ),
        migrations.AddField(
            model_name="profile",
            name="profile_pic",
            field=models.ImageField(
                blank=True,
                default="profile_pics/default_avatar.png",
                null=True,
                upload_to="profile_pics/",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="active_plan",
            field=models.CharField(default="NO ACTIVE PLAN", max_length=50),
        ),
        migrations.AlterField(
            model_name="profile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
