# Generated by Django 6.0.6 on 2026-07-04 13:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gym", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("subject", models.CharField(blank=True, max_length=200, null=True)),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name="Contact",
        ),
        migrations.RemoveField(
            model_name="membershipplan",
            name="description",
        ),
        migrations.RemoveField(
            model_name="membershipplan",
            name="duration",
        ),
        migrations.AddField(
            model_name="membershipplan",
            name="is_popular",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="trainer",
            name="certification",
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="membershipplan",
            name="price",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="trainer",
            name="experience",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="trainer",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="trainers/"),
        ),
    ]
