# Generated by Django 6.0.6 on 2026-07-05 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gym", "0002_contactmessage_delete_contact_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GymPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("price", models.IntegerField()),
                ("duration", models.CharField(default="Month", max_length=50)),
                ("feature_1", models.CharField(blank=True, max_length=200, null=True)),
                ("feature_2", models.CharField(blank=True, max_length=200, null=True)),
                ("feature_3", models.CharField(blank=True, max_length=200, null=True)),
                ("feature_4", models.CharField(blank=True, max_length=200, null=True)),
                ("is_popular", models.BooleanField(default=False)),
            ],
        ),
    ]
