# Generated by Django 6.0.6 on 2026-07-07 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gym", "0003_gymplan"),
    ]

    operations = [
        migrations.CreateModel(
            name="GymNotice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Jaise: Timing Change, Holiday, etc.", max_length=100
                    ),
                ),
                ("message", models.TextField(help_text="Apna notice yahan likhein...")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Kya is notice ko dashboard par dikhana hai?",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
