# Generated by Django 6.0.6 on 2026-07-07 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gym", "0005_gymrating"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="gymrating",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterField(
            model_name="gymrating",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
