# Generated by Django 6.0.6 on 2026-07-07 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gym", "0005_gympost_postcomment_followsystem_gymattendance_and_more"),
        ("gym", "0006_alter_gymrating_options_alter_gymrating_created_at"),
    ]

    operations = []
