# Generated by Django 6.0.6 on 2026-07-08 13:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gym", "0007_merge_20260707_2105"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "profile_pic",
                    models.ImageField(blank=True, null=True, upload_to="profile_pics/"),
                ),
                ("active_plan", models.CharField(default="Free", max_length=50)),
                ("bench_press", models.IntegerField(default=0)),
                ("squat", models.IntegerField(default=0)),
                ("deadlift", models.IntegerField(default=0)),
                (
                    "followers",
                    models.ManyToManyField(
                        blank=True, related_name="following", to="gym.profile"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gym_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="GymRating",
        ),
    ]
