# Generated by Django 6.0.6 on 2026-07-09 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gym", "0009_chatmessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="is_read",
            field=models.BooleanField(default=False),
        ),
    ]
